import { RESPONSE_CODES, ResponseCode } from './response-codes';

export const HTTP_STATUS_BY_CODE: Record<ResponseCode, number> = {
  [RESPONSE_CODES.AUTHENTICATION_REQUIRED]: 401,
  [RESPONSE_CODES.INVALID_CREDENTIALS]: 401,
  [RESPONSE_CODES.INVALID_TOKEN]: 401,
  [RESPONSE_CODES.TOKEN_EXPIRED]: 401,
  [RESPONSE_CODES.FORBIDDEN]: 403,
  [RESPONSE_CODES.VALIDATION_ERROR]: 400,
  [RESPONSE_CODES.SCHEMA_VALIDATION_ERROR]: 400,
  [RESPONSE_CODES.INVALID_RESOURCE_ID]: 400,
  [RESPONSE_CODES.RESOURCE_NOT_FOUND]: 404,
  [RESPONSE_CODES.RESOURCE_ALREADY_EXISTS]: 409,
  [RESPONSE_CODES.RATE_LIMITED]: 429,
  [RESPONSE_CODES.AI_GENERATION_FAILED]: 502,
  [RESPONSE_CODES.AI_PARSE_FAILED]: 502,
  [RESPONSE_CODES.QUEUE_JOB_FAILED]: 503,
  [RESPONSE_CODES.GENERATION_IN_PROGRESS]: 409,
  [RESPONSE_CODES.FILE_UPLOAD_FAILED]: 400,
  [RESPONSE_CODES.DATABASE_UNAVAILABLE]: 503,
  [RESPONSE_CODES.INTERNAL_SERVER_ERROR]: 500,
};

export function getHttpStatusForCode(code: string): number {
  return HTTP_STATUS_BY_CODE[code as ResponseCode] ?? 500;
}
