export const RESPONSE_CODES = {
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  FORBIDDEN: 'FORBIDDEN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  SCHEMA_VALIDATION_ERROR: 'SCHEMA_VALIDATION_ERROR',
  INVALID_RESOURCE_ID: 'INVALID_RESOURCE_ID',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
  RATE_LIMITED: 'RATE_LIMITED',
  AI_GENERATION_FAILED: 'AI_GENERATION_FAILED',
  AI_PARSE_FAILED: 'AI_PARSE_FAILED',
  QUEUE_JOB_FAILED: 'QUEUE_JOB_FAILED',
  GENERATION_IN_PROGRESS: 'GENERATION_IN_PROGRESS',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
  DATABASE_UNAVAILABLE: 'DATABASE_UNAVAILABLE',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export type ResponseCode = typeof RESPONSE_CODES[keyof typeof RESPONSE_CODES];
